
const strings = {
    de:{
        distance: 'Distanz: ',
        duration: 'Dauer: ',
        startOn: 'Starten auf ',
        arrived: 'Ziel erreicht',
        arrivedAt: 'Ziel erreicht auf ',
        after: 'nach ',
        turnLeft: 'nach links',
        turnRight: 'nach rechts',
        uturn: 'wenden',
        straightAhead: 'weiter geradeaus',
        turnLeftTo: 'nach links auf ',
        turnRightTo: 'nach rechts auf ',
        uturnTo: 'wenden auf ',
        straightAheadTo: 'geradeaus auf ',
    },
    en:{
        distance: 'Distance: ',
        duration: 'Duration: ',
        startOn: 'Start on ',
        arrived: 'Arrived',
        arrivedAt: 'Arrived on ',
        after: 'after ',
        turnLeft: 'turn left',
        turnRight: 'turn right',
        uturn: 'uturn',
        straightAhead: 'straight ahead',
        turnLeftTo: 'turn left on ',
        turnRightTo: 'turn right on ',
        uturnTo: 'uturn on ',
        straightAheadTo: 'straight ahead on ',
    }
}
